---
# Disable linter for this whole directory.
ignore_path: True

# Fine-grained control which tasks should be run on path.
# Either define whitelist or blacklist.
whitelisted_tasks: []
blacklisted_tasks: []
...
